ALTER TABLE "Cv"
ADD COLUMN "isPublished" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "publishedData" JSONB,
ADD COLUMN "shareToken" TEXT,
ADD COLUMN "shareEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "publishedAt" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX "Cv_shareToken_key" ON "Cv"("shareToken");
